BUILD_BITS=32
BUILD_TYPE=base
!INCLUDE $(BASEDIR)\inc\master.mk

CFLAGS     = -DWIN32 -DCON -Di386 -D_X86_ -D_NTWIN -W3 -Gs -D_DEBUG -Zi
CVXDFLAGS  = -Zdp -Gs -c -DIS_32 -Zl -DDEBLEVEL=1 -DDEBUG
LFLAGS     = -machine:i386 -debug:full -debugtype:cv /PDB:BIN\SENTINEL.PDB -subsystem:console kernel32.lib user32.lib shell32.lib
AFLAGS     = -coff -DBLD_COFF -DIS_32 -W2 -Zd -c -Cx -DMASM6 -DDEBLEVEL=1 -DDEBUG

all: direxist bin\SENTINEL.vxd

direxist:
        if not exist bin\nul    md bin

bin\sentinel.res: sentinel.rc
        $(RC16B) -r -Fo$@ sentinel.rc

bin\SENTINEL.obj: SENTINEL.c
        cl $(CVXDFLAGS) -Fo$@ %s

bin\cvxdctrl.obj: cvxdctrl.asm
        ml $(AFLAGS) -Fo$@ %s

bin\SENTINEL.vxd: bin\SENTINEL.obj bin\cvxdctrl.obj bin\sentinel.res cvxd.def
        echo >NUL @<<SENTINEL.crf
-MACHINE:i386 -DEBUG:FULL -PDB:bin\SENTINEL.PDB
-DEF:cvxd.def -OUT:bin\SENTINEL.vxd -MAP:bin\SENTINEL.map
-VXD $(BASEDIR)\lib\i386\free\vxdwraps.clb bin\SENTINEL.obj bin\cvxdctrl.obj
<<
        link @SENTINEL.crf
        cd bin
        adrc2vxd sentinel.vxd sentinel.res
        mapsym SENTINEL.MAP
        cd ..

clean:
		-@del bin\*.obj
		-@del bin\*.vxd
		-@del bin\*.exp
		-@del bin\*.map
		-@del bin\*.sym
		-@del bin\*.lib
		-@del bin\*.pdb
		-@del bin\*.res
		-@rd  bin